# Generated by Django 5.1.7 on 2025-04-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom del producte')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preu antic del producte')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preu del producte')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imatge del producte')),
            ],
            options={
                'unique_together': {('name', 'image')},
            },
        ),
    ]
