# Generated by Django 5.1.7 on 2025-03-24 18:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteproducts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproducts',
            unique_together={('user', 'product_id')},
        ),
    ]
