# Generated by Django 5.1.7 on 2025-03-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_favoriteproducts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproducts',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteproducts',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteproducts',
            name='old_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteproducts',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
