# Generated by Django 5.1.7 on 2025-03-27 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shoppingcartlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartlist',
            unique_together={('user', 'product_id')},
        ),
    ]
