# Generated by Django 5.1.7 on 2025-04-03 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_favoriteproducts_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shoppingcartlist',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grupfamiliar'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartlist',
            unique_together={('user', 'product_id', 'group_id')},
        ),
    ]
