# Generated by Django 5.1.7 on 2025-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_history_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupfamiliar',
            name='invite_token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
