# Generated by Django 5.1.7 on 2025-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_grupfamiliar_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartlist',
            name='supermarket',
            field=models.BooleanField(default=0),
        ),
    ]
