# Generated by Django 5.1.7 on 2025-05-08 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mercadolivrecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadolivrecategory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mercadolivrecategory',
            name='category_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadolivrecategory',
            name='next_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
