# Generated by Django 5.1.7 on 2025-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_mercadolivrecategory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolivrecategory',
            name='next_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
