# Generated by Django 5.1.7 on 2025-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_mercadolivrecategory_next_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartlist',
            name='supermarket',
            field=models.IntegerField(default=0),
        ),
    ]
