# Generated by Django 5.1.7 on 2025-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_favoriteproducts_image_favoriteproducts_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproducts',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
