# Generated by Django 5.1.7 on 2025-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_favoriteproducts_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproducts',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
