# Generated by Django 5.1.7 on 2025-04-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_usuariogrupo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproducts',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grupfamiliar'),
        ),
    ]
