# Generated by Django 5.1.7 on 2025-04-03 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_favoriteproducts_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproducts',
            unique_together={('user', 'product_id', 'group_id')},
        ),
    ]
