# Generated by Django 5.1.7 on 2025-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apiproducts',
            unique_together={('name', 'image_url', 'price')},
        ),
        migrations.AddField(
            model_name='apiproducts',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Imatge del producte'),
        ),
        migrations.RemoveField(
            model_name='apiproducts',
            name='image',
        ),
    ]
